'use client';
import { useEffect, useRef, useState, type MouseEvent, type ReactNode, type CSSProperties } from 'react';
import { usePathname, useRouter } from 'next/navigation';
import { Dialog, DialogContent, DialogTitle, DialogDescription, DialogClose } from '@/components/ui/dialog';
import { covers, profile, projects, type Project } from '@/data/portfolio';
const num = (n:number) => String(n).padStart(2,'0');
const reduced = () => window.matchMedia('(prefers-reduced-motion: reduce)').matches;

function Artwork({src,alt,priority=false,width=3508,height=2480}:{src:string;alt:string;priority?:boolean;width?:number;height?:number}) {
 const [failed,setFailed] = useState(false); const imageRef=useRef<HTMLImageElement>(null);
 useEffect(()=>{setFailed(!!imageRef.current?.complete && imageRef.current.naturalWidth===0);},[src]);
 return failed ? <span className="image-error"><span>IMAGE UNAVAILABLE</span><small>Please check this portfolio page.</small></span> : <img ref={imageRef} src={src} alt={alt} loading={priority?'eager':'lazy'} fetchPriority={priority?'high':'auto'} decoding="async" width={width} height={height} onError={()=>setFailed(true)}/>;
}

export default function Portfolio(){
 const pathname=usePathname() || '/'; const router=useRouter();
 const project=projects.find(p=>pathname===`/work/${p.id}`);
 const [menu,setMenu]=useState(false); const [leaving,setLeaving]=useState(false); const [page,setPage]=useState(1); const [cover,setCover]=useState(0);
 const [lightbox,setLightbox]=useState<{src:string;alt:string;index:number}|null>(null); const [zoom,setZoom]=useState(1);
 const indexPosition=useRef<number|null>(null);
 const timeout=useRef<ReturnType<typeof setTimeout>|null>(null); const pending=useRef<string|null>(null); const positions=useRef<Record<string,number>>({}); const current=useRef(pathname); const opener=useRef<HTMLElement|null>(null); const menuOpener=useRef<HTMLButtonElement>(null); const stage=useRef<HTMLDivElement>(null); const pinch=useRef<{distance:number;zoom:number}|null>(null);
 useEffect(()=>{const old=history.scrollRestoration;history.scrollRestoration='manual';const save=()=>{positions.current[current.current]=window.scrollY;};window.addEventListener('scroll',save,{passive:true});return()=>{history.scrollRestoration=old;window.removeEventListener('scroll',save);if(timeout.current)clearTimeout(timeout.current);};},[]);
 useEffect(()=>{
  current.current=pathname;setPage(1);setLeaving(false);setLightbox(null);
  const target=pending.current;pending.current=null;
  const frame=requestAnimationFrame(()=>{const hash=target?.split('#')[1]||location.hash.slice(1);if(!target&&positions.current[pathname]!==undefined)window.scrollTo({top:positions.current[pathname],behavior:'instant'});else if(hash==='work'&&indexPosition.current!==null)window.scrollTo({top:indexPosition.current,behavior:'instant'});else if(hash)document.getElementById(hash)?.scrollIntoView({behavior:'instant'});else window.scrollTo({top:0,behavior:'instant'});});
  return()=>cancelAnimationFrame(frame);
 },[pathname]);
 useEffect(()=>{if(!project)return; const update=()=>{let nearest=1,best=Infinity; document.querySelectorAll<HTMLElement>('[data-page]').forEach(el=>{const r=el.getBoundingClientRect();const middle=window.innerHeight*.5;const distance=r.top<=middle&&r.bottom>=middle?0:Math.min(Math.abs(r.top-middle),Math.abs(r.bottom-middle));if(distance<best){best=distance;nearest=Number(el.dataset.page);}});setPage(nearest);};let frame=0;const schedule=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(update);};const observer=new IntersectionObserver(schedule,{threshold:[0,.25,.5,.75,1]});document.querySelectorAll('[data-page]').forEach(el=>observer.observe(el));window.addEventListener('scroll',schedule,{passive:true});window.addEventListener('resize',schedule);update();return()=>{observer.disconnect();cancelAnimationFrame(frame);window.removeEventListener('scroll',schedule);window.removeEventListener('resize',schedule);};},[project]);
 function navigate(url:string){setMenu(false);if(timeout.current)clearTimeout(timeout.current);const destination=url.split('#')[0]||'/';if(pathname==='/'&&destination.startsWith('/work/'))indexPosition.current=window.scrollY;if(destination===pathname){setLeaving(false);pending.current=null;history.pushState(null,'',url);const id=url.split('#')[1];if(id)document.getElementById(id)?.scrollIntoView({behavior:reduced()?'instant':'smooth'});else window.scrollTo({top:0,behavior:reduced()?'instant':'smooth'});return;}pending.current=url;setLeaving(true);timeout.current=setTimeout(()=>router.push(url,{scroll:false}),reduced()?0:250);}
 function Nav({to,children,className='',label,style}:{to:string;children:ReactNode;className?:string;label?:string;style?:CSSProperties}) {return <a href={to} className={className} style={style} aria-label={label} onClick={(e:MouseEvent<HTMLAnchorElement>)=>{if(e.metaKey||e.ctrlKey||e.shiftKey||e.altKey||e.button!==0)return;e.preventDefault();navigate(to);}}>{children}</a>;}
 const next=project?projects[projects.indexOf(project)+1]:null;
 const fitImageHeight=()=>{const el=stage.current;const img=el?.querySelector('img');if(!el||!img)return 1;const pad=parseFloat(getComputedStyle(el).paddingTop)*2;return Math.min(el.clientHeight-pad,(el.clientWidth-pad)*img.naturalHeight/img.naturalWidth);};
 const openImage=(src:string,alt:string,index:number,target:HTMLElement)=>{opener.current=target;setZoom(1);setLightbox({src,alt,index});};
 return <>
  <a className="skip-link" href="#main">Skip to content</a>
  <header><Nav to="/#cover">{profile.name}</Nav><span>PORTFOLIO / {profile.year}</span><button ref={menuOpener} onClick={()=>setMenu(true)} aria-haspopup="dialog" aria-expanded={menu}>MENU <span className="menu-plus">＋</span></button></header>
  <Dialog open={menu} onOpenChange={setMenu}><DialogContent className="menu-dialog" showCloseButton={false} onCloseAutoFocus={e=>{e.preventDefault();menuOpener.current?.focus();}}><DialogTitle className="eyebrow">PORTFOLIO / NAVIGATION</DialogTitle><DialogDescription className="sr-only">Navigate the portfolio sections.</DialogDescription><DialogClose className="dialog-close">CLOSE ×</DialogClose><nav>{[['Cover','cover'],['About','about'],['Work','work'],['Contact','contact']].map(([label,id],i)=><Nav to={`/#${id}`} key={id}><small>{num(i+1)}</small><span>{label}</span><span className="arrow">↗</span></Nav>)}</nav><p className="menu-foot">{profile.name}<span>{profile.year}</span></p></DialogContent></Dialog>
  {project&&<aside className="reading-status" style={{"--project-accent":project.accent} as CSSProperties} aria-label="Reading progress"><span>PROJECT {num(projects.indexOf(project)+1)}</span><span>{num(page)} <i>/ {num(project.pages.length)}</i></span></aside>}
  <main id="main" style={{"--project-accent":project?.accent||"#713B20"} as CSSProperties} className={`route ${leaving?'leaving':''}`} key={pathname}>
  {!project&&pathname==='/'?<>
   <section className="cover" id="cover"><span className="rail">INDEPENDENT DESIGNER<br/>SELECTED WORKS, {profile.year}</span><Artwork src={covers[cover].src} alt={covers[cover].alt} width={covers[cover].width} height={covers[cover].height} priority/><Nav to="/#about" className="explore">SCROLL TO EXPLORE <span>↓</span></Nav><span className="cover-count">01 — {num(projects.length)}</span>{covers.length>1&&<div className="cover-selector">{covers.map((c,i)=><button key={c.src} aria-label={`Show cover ${i+1}`} aria-pressed={cover===i} onClick={()=>setCover(i)}>{num(i+1)}</button>)}</div>}</section>
   <section id="about" className="section about"><div className="section-label"><span>01 / ABOUT</span><span>A PRACTICE IN PROGRESS</span></div><h1>Ideas take shape.<br/><em>Across disciplines.</em></h1><div className="about-grid"><div className="about-name">{profile.name}<span>DESIGNER / IMAGE MAKER</span></div><div className="bio"><p>{profile.introduction}</p><p>{profile.biography}</p></div><div className="fields"><h2>FIELDS</h2>{profile.fields.map(f=><span key={f}>{f}</span>)}</div></div><div className="about-contact"><span>CONTACT</span><a href={`mailto:${profile.email}`}>{profile.email} ↗</a>{profile.links.filter(l=>l.url).map(l=><a key={l.url} href={l.url} target="_blank" rel="noreferrer">{l.label} ↗</a>)}</div></section>
   <section className="section index" id="work"><div className="section-label"><span>02 / SELECTED WORKS</span><span>{profile.year} / {num(projects.length)} PROJECTS</span></div><div className="index-heading"><h2>A selection<br/>of explorations<span className="serif">.</span></h2><span className="index-note">IDEAS, PROCESSES<br/>& PERSPECTIVES</span></div><div className="index-columns"><span>NO.</span><span>PROJECT</span><span>DISCIPLINE</span><span>YEAR</span><span/></div><div>{projects.map((p,i)=><Nav key={p.id} to={`/work/${p.id}`} className="project-row" style={{"--project-accent":p.accent} as CSSProperties}><span className="project-number">{num(i+1)}</span><h3>{p.title}<small className="index-page-count">{num(p.pages.length)} PAGES</small></h3><span className="category">{p.category}</span><span className="year">{p.year}</span><span className="arrow">↗</span></Nav>)}</div><div className="index-bottom"><span>READ AT YOUR OWN PACE.</span><span>↓</span></div></section>
   <Contact Nav={Nav}/>
  </>:project?<>
   <section className="project-intro"><Nav to="/#work" className="back-link">← SELECTED WORKS</Nav><div className="intro-rule"><span>PROJECT {num(projects.indexOf(project)+1)}</span><span>{num(project.pages.length)} PAGES / LANDSCAPE A4</span></div><div className="intro-grid"><div><h1>{project.title}</h1>{project.subtitle&&<p className="subtitle">{project.subtitle}</p>}</div><div className="project-details"><div className="meta-pair"><Info title="YEAR">{project.year}</Info><Info title="CATEGORY">{project.category}</Info></div><Info title="DESCRIPTION"><p>{project.description}</p></Info><div className="meta-pair"><Info title="ROLE">{project.role}</Info><Info title="TOOLS">{project.tools.length ? project.tools.join(' / ') : '—'}</Info></div></div></div><div className="reading-hint"><span>SCROLL TO READ</span><span>↓</span></div></section>
   <div className="pages">{project.pages.map((src,i)=><figure key={src} data-page={i+1} className="artwork"><button className="artwork-open" aria-label={`Open ${project.title}, page ${i+1} in fullscreen`} onClick={e=>{if(e.currentTarget.querySelector("img")?.naturalWidth)openImage(src,project.pageAlt[i]||`${project.title}, page ${i+1}`,i+1,e.currentTarget);}}><Artwork src={src} alt={project.pageAlt[i]||`${project.title}, page ${i+1}`} priority={i===0}/><span className="view-hint">VIEW FULLSCREEN ↗</span></button><figcaption><span>{project.title.toUpperCase()}</span><span>{num(i+1)} / {num(project.pages.length)}</span></figcaption></figure>)}</div>
   <section className="project-end"><div className="section-label"><span>END OF PROJECT {num(projects.indexOf(project)+1)}</span><span>{num(project.pages.length)} / {num(project.pages.length)}</span></div>{next?<Nav className="next-project" to={`/work/${next.id}`}><small>NEXT PROJECT</small><span>{next.title}<span className="arrow">↗</span></span><em>{next.category}</em></Nav>:<Nav className="next-project" to="/#contact"><small>THANK YOU FOR READING</small><span>Let’s connect.<span className="arrow">↗</span></span></Nav>}<div className="end-links"><Nav to="/#work">← BACK TO PROJECT INDEX</Nav><Nav to="/#cover">BACK TO COVER ↑</Nav></div></section>
  </>:null}
  </main>
  <Dialog open={!!lightbox} onOpenChange={open=>{if(!open)setLightbox(null);}}><DialogContent className="lightbox-dialog" showCloseButton={false} onCloseAutoFocus={e=>{e.preventDefault();opener.current?.focus({preventScroll:true});}}><DialogTitle className="sr-only">{lightbox?.alt||'Fullscreen artwork'}</DialogTitle><DialogDescription className="sr-only">Use Original size to enlarge. Scroll to explore the image, pinch on touchscreens, or press Escape to close.</DialogDescription><div className="lightbox-toolbar"><span>{num(lightbox?.index||1)} / {num(project?.pages.length||0)}</span><button onClick={()=>{setZoom(zoom===1?Math.max(1,(stage.current?.querySelector('img')?.naturalHeight||1)/fitImageHeight()):1);stage.current?.scrollTo(0,0);}}>{zoom===1?'ORIGINAL SIZE ↗':'FIT TO SCREEN ↙'}</button><DialogClose>CLOSE ×</DialogClose></div><div ref={stage} className={`lightbox-stage ${zoom>1?'zoomed':''}`} onClick={e=>{if(e.target===e.currentTarget)setLightbox(null);}} onTouchStart={e=>{if(e.touches.length===2){pinch.current={distance:Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY),zoom};}}} onTouchMove={e=>{if(e.touches.length===2&&pinch.current){const distance=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);setZoom(Math.max(1,Math.min(4,pinch.current.zoom*distance/pinch.current.distance)));}}} onTouchEnd={()=>{pinch.current=null;}}>{lightbox&&<img src={lightbox.src} alt={lightbox.alt} style={zoom>1?{height:`${fitImageHeight()*zoom}px`,maxWidth:'none',maxHeight:'none',width:'auto'}:undefined} draggable={false}/>}</div></DialogContent></Dialog>
 </>;
}
function Info({title,children}:{title:string;children:ReactNode}){return <div className="info"><h2>{title}</h2><div>{children}</div></div>;}
function Contact({Nav}:{Nav:React.ComponentType<{to:string;children:ReactNode;className?:string}>}) { return <section id="contact" className="section contact"><div className="section-label"><span>03 / CONTACT</span><span>OPEN TO CONVERSATION</span></div><h2>Let’s make<br/><em>something meaningful.</em></h2><a className="email" href={`mailto:${profile.email}`}>{profile.email}<span className="arrow">↗</span></a><div className="contact-links">{profile.links.filter(l=>l.url).map(l=><a key={l.url} href={l.url} target="_blank" rel="noreferrer">{l.label} ↗</a>)}</div><footer><span>© {profile.year} {profile.name}</span><span>SELECTED WORKS / PORTFOLIO</span><Nav to="/#cover">BACK TO COVER ↑</Nav></footer></section>; }
